/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as ApiCoursesRouteImport } from './routes/api/courses'
import { Route as CourseCourseNameRouteImport } from './routes/course/$courseName'
import { Route as ApiCanvasSplatRouteImport } from './routes/api.canvas.$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as CourseCourseNameIndexRouteImport } from './routes/course/$courseName/index'
import { Route as CourseCourseNameSettingsRouteImport } from './routes/course/$courseName/settings'
import { Route as CourseCourseNameLectureLectureDayIndexRouteImport } from './routes/course/$courseName/lecture/$lectureDay/index'
import { Route as CourseCourseNameLectureLectureDayPreviewRouteImport } from './routes/course/$courseName/lecture/$lectureDay/preview'
import { Route as CourseCourseNameModulesModuleNameAssignmentAssignmentNameRouteImport } from './routes/course/$courseName/modules/$moduleName/assignment.$assignmentName'
import { Route as CourseCourseNameModulesModuleNamePagePageNameRouteImport } from './routes/course/$courseName/modules/$moduleName/page.$pageName'
import { Route as CourseCourseNameModulesModuleNameQuizQuizNameRouteImport } from './routes/course/$courseName/modules/$moduleName/quiz.$quizName'
import { Route as CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRouteImport } from './routes/course/$courseName/modules/$moduleName/assignment.$assignmentName_.compare'
import { Route as CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRouteImport } from './routes/course/$courseName/modules/$moduleName/assignment.$assignmentName_.history'
import { Route as CourseCourseNameModulesModuleNamePagePageNameHistoryRouteImport } from './routes/course/$courseName/modules/$moduleName/page.$pageName_.history'
import { Route as CourseCourseNameModulesModuleNameQuizQuizNameCompareRouteImport } from './routes/course/$courseName/modules/$moduleName/quiz.$quizName_.compare'
import { Route as CourseCourseNameModulesModuleNameQuizQuizNameHistoryRouteImport } from './routes/course/$courseName/modules/$moduleName/quiz.$quizName_.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesRoute = ApiCoursesRouteImport.update({
  id: '/api/courses',
  path: '/api/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseNameRoute = CourseCourseNameRouteImport.update({
  id: '/course/$courseName',
  path: '/course/$courseName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasSplatRoute = ApiCanvasSplatRouteImport.update({
  id: '/api/canvas/$',
  path: '/api/canvas/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseNameIndexRoute = CourseCourseNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseCourseNameRoute,
} as any)
const CourseCourseNameSettingsRoute =
  CourseCourseNameSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => CourseCourseNameRoute,
  } as any)
const CourseCourseNameLectureLectureDayIndexRoute =
  CourseCourseNameLectureLectureDayIndexRouteImport.update({
    id: '/lecture/$lectureDay/',
    path: '/lecture/$lectureDay/',
    getParentRoute: () => CourseCourseNameRoute,
  } as any)
const CourseCourseNameLectureLectureDayPreviewRoute =
  CourseCourseNameLectureLectureDayPreviewRouteImport.update({
    id: '/lecture/$lectureDay/preview',
    path: '/lecture/$lectureDay/preview',
    getParentRoute: () => CourseCourseNameRoute,
  } as any)
const CourseCourseNameModulesModuleNameAssignmentAssignmentNameRoute =
  CourseCourseNameModulesModuleNameAssignmentAssignmentNameRouteImport.update({
    id: '/modules/$moduleName/assignment/$assignmentName',
    path: '/modules/$moduleName/assignment/$assignmentName',
    getParentRoute: () => CourseCourseNameRoute,
  } as any)
const CourseCourseNameModulesModuleNamePagePageNameRoute =
  CourseCourseNameModulesModuleNamePagePageNameRouteImport.update({
    id: '/modules/$moduleName/page/$pageName',
    path: '/modules/$moduleName/page/$pageName',
    getParentRoute: () => CourseCourseNameRoute,
  } as any)
const CourseCourseNameModulesModuleNameQuizQuizNameRoute =
  CourseCourseNameModulesModuleNameQuizQuizNameRouteImport.update({
    id: '/modules/$moduleName/quiz/$quizName',
    path: '/modules/$moduleName/quiz/$quizName',
    getParentRoute: () => CourseCourseNameRoute,
  } as any)
const CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRoute =
  CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRouteImport.update(
    {
      id: '/modules/$moduleName/assignment/$assignmentName_/compare',
      path: '/modules/$moduleName/assignment/$assignmentName/compare',
      getParentRoute: () => CourseCourseNameRoute,
    } as any,
  )
const CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRoute =
  CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRouteImport.update(
    {
      id: '/modules/$moduleName/assignment/$assignmentName_/history',
      path: '/modules/$moduleName/assignment/$assignmentName/history',
      getParentRoute: () => CourseCourseNameRoute,
    } as any,
  )
const CourseCourseNameModulesModuleNamePagePageNameHistoryRoute =
  CourseCourseNameModulesModuleNamePagePageNameHistoryRouteImport.update({
    id: '/modules/$moduleName/page/$pageName_/history',
    path: '/modules/$moduleName/page/$pageName/history',
    getParentRoute: () => CourseCourseNameRoute,
  } as any)
const CourseCourseNameModulesModuleNameQuizQuizNameCompareRoute =
  CourseCourseNameModulesModuleNameQuizQuizNameCompareRouteImport.update({
    id: '/modules/$moduleName/quiz/$quizName_/compare',
    path: '/modules/$moduleName/quiz/$quizName/compare',
    getParentRoute: () => CourseCourseNameRoute,
  } as any)
const CourseCourseNameModulesModuleNameQuizQuizNameHistoryRoute =
  CourseCourseNameModulesModuleNameQuizQuizNameHistoryRouteImport.update({
    id: '/modules/$moduleName/quiz/$quizName_/history',
    path: '/modules/$moduleName/quiz/$quizName/history',
    getParentRoute: () => CourseCourseNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRoute
  '/api/courses': typeof ApiCoursesRoute
  '/course/$courseName': typeof CourseCourseNameRouteWithChildren
  '/api/canvas/$': typeof ApiCanvasSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/course/$courseName/settings': typeof CourseCourseNameSettingsRoute
  '/course/$courseName/': typeof CourseCourseNameIndexRoute
  '/course/$courseName/lecture/$lectureDay/preview': typeof CourseCourseNameLectureLectureDayPreviewRoute
  '/course/$courseName/lecture/$lectureDay/': typeof CourseCourseNameLectureLectureDayIndexRoute
  '/course/$courseName/modules/$moduleName/assignment/$assignmentName': typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameRoute
  '/course/$courseName/modules/$moduleName/page/$pageName': typeof CourseCourseNameModulesModuleNamePagePageNameRoute
  '/course/$courseName/modules/$moduleName/quiz/$quizName': typeof CourseCourseNameModulesModuleNameQuizQuizNameRoute
  '/course/$courseName/modules/$moduleName/assignment/$assignmentName/compare': typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRoute
  '/course/$courseName/modules/$moduleName/assignment/$assignmentName/history': typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRoute
  '/course/$courseName/modules/$moduleName/page/$pageName/history': typeof CourseCourseNameModulesModuleNamePagePageNameHistoryRoute
  '/course/$courseName/modules/$moduleName/quiz/$quizName/compare': typeof CourseCourseNameModulesModuleNameQuizQuizNameCompareRoute
  '/course/$courseName/modules/$moduleName/quiz/$quizName/history': typeof CourseCourseNameModulesModuleNameQuizQuizNameHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRoute
  '/api/courses': typeof ApiCoursesRoute
  '/api/canvas/$': typeof ApiCanvasSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/course/$courseName/settings': typeof CourseCourseNameSettingsRoute
  '/course/$courseName': typeof CourseCourseNameIndexRoute
  '/course/$courseName/lecture/$lectureDay/preview': typeof CourseCourseNameLectureLectureDayPreviewRoute
  '/course/$courseName/lecture/$lectureDay': typeof CourseCourseNameLectureLectureDayIndexRoute
  '/course/$courseName/modules/$moduleName/assignment/$assignmentName': typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameRoute
  '/course/$courseName/modules/$moduleName/page/$pageName': typeof CourseCourseNameModulesModuleNamePagePageNameRoute
  '/course/$courseName/modules/$moduleName/quiz/$quizName': typeof CourseCourseNameModulesModuleNameQuizQuizNameRoute
  '/course/$courseName/modules/$moduleName/assignment/$assignmentName/compare': typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRoute
  '/course/$courseName/modules/$moduleName/assignment/$assignmentName/history': typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRoute
  '/course/$courseName/modules/$moduleName/page/$pageName/history': typeof CourseCourseNameModulesModuleNamePagePageNameHistoryRoute
  '/course/$courseName/modules/$moduleName/quiz/$quizName/compare': typeof CourseCourseNameModulesModuleNameQuizQuizNameCompareRoute
  '/course/$courseName/modules/$moduleName/quiz/$quizName/history': typeof CourseCourseNameModulesModuleNameQuizQuizNameHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRoute
  '/api/courses': typeof ApiCoursesRoute
  '/course/$courseName': typeof CourseCourseNameRouteWithChildren
  '/api/canvas/$': typeof ApiCanvasSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/course/$courseName/settings': typeof CourseCourseNameSettingsRoute
  '/course/$courseName/': typeof CourseCourseNameIndexRoute
  '/course/$courseName/lecture/$lectureDay/preview': typeof CourseCourseNameLectureLectureDayPreviewRoute
  '/course/$courseName/lecture/$lectureDay/': typeof CourseCourseNameLectureLectureDayIndexRoute
  '/course/$courseName/modules/$moduleName/assignment/$assignmentName': typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameRoute
  '/course/$courseName/modules/$moduleName/page/$pageName': typeof CourseCourseNameModulesModuleNamePagePageNameRoute
  '/course/$courseName/modules/$moduleName/quiz/$quizName': typeof CourseCourseNameModulesModuleNameQuizQuizNameRoute
  '/course/$courseName/modules/$moduleName/assignment/$assignmentName_/compare': typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRoute
  '/course/$courseName/modules/$moduleName/assignment/$assignmentName_/history': typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRoute
  '/course/$courseName/modules/$moduleName/page/$pageName_/history': typeof CourseCourseNameModulesModuleNamePagePageNameHistoryRoute
  '/course/$courseName/modules/$moduleName/quiz/$quizName_/compare': typeof CourseCourseNameModulesModuleNameQuizQuizNameCompareRoute
  '/course/$courseName/modules/$moduleName/quiz/$quizName_/history': typeof CourseCourseNameModulesModuleNameQuizQuizNameHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/errors'
    | '/api/courses'
    | '/course/$courseName'
    | '/api/canvas/$'
    | '/api/trpc/$'
    | '/course/$courseName/settings'
    | '/course/$courseName/'
    | '/course/$courseName/lecture/$lectureDay/preview'
    | '/course/$courseName/lecture/$lectureDay/'
    | '/course/$courseName/modules/$moduleName/assignment/$assignmentName'
    | '/course/$courseName/modules/$moduleName/page/$pageName'
    | '/course/$courseName/modules/$moduleName/quiz/$quizName'
    | '/course/$courseName/modules/$moduleName/assignment/$assignmentName/compare'
    | '/course/$courseName/modules/$moduleName/assignment/$assignmentName/history'
    | '/course/$courseName/modules/$moduleName/page/$pageName/history'
    | '/course/$courseName/modules/$moduleName/quiz/$quizName/compare'
    | '/course/$courseName/modules/$moduleName/quiz/$quizName/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/errors'
    | '/api/courses'
    | '/api/canvas/$'
    | '/api/trpc/$'
    | '/course/$courseName/settings'
    | '/course/$courseName'
    | '/course/$courseName/lecture/$lectureDay/preview'
    | '/course/$courseName/lecture/$lectureDay'
    | '/course/$courseName/modules/$moduleName/assignment/$assignmentName'
    | '/course/$courseName/modules/$moduleName/page/$pageName'
    | '/course/$courseName/modules/$moduleName/quiz/$quizName'
    | '/course/$courseName/modules/$moduleName/assignment/$assignmentName/compare'
    | '/course/$courseName/modules/$moduleName/assignment/$assignmentName/history'
    | '/course/$courseName/modules/$moduleName/page/$pageName/history'
    | '/course/$courseName/modules/$moduleName/quiz/$quizName/compare'
    | '/course/$courseName/modules/$moduleName/quiz/$quizName/history'
  id:
    | '__root__'
    | '/'
    | '/errors'
    | '/api/courses'
    | '/course/$courseName'
    | '/api/canvas/$'
    | '/api/trpc/$'
    | '/course/$courseName/settings'
    | '/course/$courseName/'
    | '/course/$courseName/lecture/$lectureDay/preview'
    | '/course/$courseName/lecture/$lectureDay/'
    | '/course/$courseName/modules/$moduleName/assignment/$assignmentName'
    | '/course/$courseName/modules/$moduleName/page/$pageName'
    | '/course/$courseName/modules/$moduleName/quiz/$quizName'
    | '/course/$courseName/modules/$moduleName/assignment/$assignmentName_/compare'
    | '/course/$courseName/modules/$moduleName/assignment/$assignmentName_/history'
    | '/course/$courseName/modules/$moduleName/page/$pageName_/history'
    | '/course/$courseName/modules/$moduleName/quiz/$quizName_/compare'
    | '/course/$courseName/modules/$moduleName/quiz/$quizName_/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorsRoute: typeof ErrorsRoute
  ApiCoursesRoute: typeof ApiCoursesRoute
  CourseCourseNameRoute: typeof CourseCourseNameRouteWithChildren
  ApiCanvasSplatRoute: typeof ApiCanvasSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses': {
      id: '/api/courses'
      path: '/api/courses'
      fullPath: '/api/courses'
      preLoaderRoute: typeof ApiCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseName': {
      id: '/course/$courseName'
      path: '/course/$courseName'
      fullPath: '/course/$courseName'
      preLoaderRoute: typeof CourseCourseNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas/$': {
      id: '/api/canvas/$'
      path: '/api/canvas/$'
      fullPath: '/api/canvas/$'
      preLoaderRoute: typeof ApiCanvasSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseName/': {
      id: '/course/$courseName/'
      path: '/'
      fullPath: '/course/$courseName/'
      preLoaderRoute: typeof CourseCourseNameIndexRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/settings': {
      id: '/course/$courseName/settings'
      path: '/settings'
      fullPath: '/course/$courseName/settings'
      preLoaderRoute: typeof CourseCourseNameSettingsRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/lecture/$lectureDay/': {
      id: '/course/$courseName/lecture/$lectureDay/'
      path: '/lecture/$lectureDay'
      fullPath: '/course/$courseName/lecture/$lectureDay/'
      preLoaderRoute: typeof CourseCourseNameLectureLectureDayIndexRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/lecture/$lectureDay/preview': {
      id: '/course/$courseName/lecture/$lectureDay/preview'
      path: '/lecture/$lectureDay/preview'
      fullPath: '/course/$courseName/lecture/$lectureDay/preview'
      preLoaderRoute: typeof CourseCourseNameLectureLectureDayPreviewRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/modules/$moduleName/assignment/$assignmentName': {
      id: '/course/$courseName/modules/$moduleName/assignment/$assignmentName'
      path: '/modules/$moduleName/assignment/$assignmentName'
      fullPath: '/course/$courseName/modules/$moduleName/assignment/$assignmentName'
      preLoaderRoute: typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/modules/$moduleName/page/$pageName': {
      id: '/course/$courseName/modules/$moduleName/page/$pageName'
      path: '/modules/$moduleName/page/$pageName'
      fullPath: '/course/$courseName/modules/$moduleName/page/$pageName'
      preLoaderRoute: typeof CourseCourseNameModulesModuleNamePagePageNameRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/modules/$moduleName/quiz/$quizName': {
      id: '/course/$courseName/modules/$moduleName/quiz/$quizName'
      path: '/modules/$moduleName/quiz/$quizName'
      fullPath: '/course/$courseName/modules/$moduleName/quiz/$quizName'
      preLoaderRoute: typeof CourseCourseNameModulesModuleNameQuizQuizNameRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/modules/$moduleName/assignment/$assignmentName_/compare': {
      id: '/course/$courseName/modules/$moduleName/assignment/$assignmentName_/compare'
      path: '/modules/$moduleName/assignment/$assignmentName/compare'
      fullPath: '/course/$courseName/modules/$moduleName/assignment/$assignmentName/compare'
      preLoaderRoute: typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/modules/$moduleName/assignment/$assignmentName_/history': {
      id: '/course/$courseName/modules/$moduleName/assignment/$assignmentName_/history'
      path: '/modules/$moduleName/assignment/$assignmentName/history'
      fullPath: '/course/$courseName/modules/$moduleName/assignment/$assignmentName/history'
      preLoaderRoute: typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/modules/$moduleName/page/$pageName_/history': {
      id: '/course/$courseName/modules/$moduleName/page/$pageName_/history'
      path: '/modules/$moduleName/page/$pageName/history'
      fullPath: '/course/$courseName/modules/$moduleName/page/$pageName/history'
      preLoaderRoute: typeof CourseCourseNameModulesModuleNamePagePageNameHistoryRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/modules/$moduleName/quiz/$quizName_/compare': {
      id: '/course/$courseName/modules/$moduleName/quiz/$quizName_/compare'
      path: '/modules/$moduleName/quiz/$quizName/compare'
      fullPath: '/course/$courseName/modules/$moduleName/quiz/$quizName/compare'
      preLoaderRoute: typeof CourseCourseNameModulesModuleNameQuizQuizNameCompareRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
    '/course/$courseName/modules/$moduleName/quiz/$quizName_/history': {
      id: '/course/$courseName/modules/$moduleName/quiz/$quizName_/history'
      path: '/modules/$moduleName/quiz/$quizName/history'
      fullPath: '/course/$courseName/modules/$moduleName/quiz/$quizName/history'
      preLoaderRoute: typeof CourseCourseNameModulesModuleNameQuizQuizNameHistoryRouteImport
      parentRoute: typeof CourseCourseNameRoute
    }
  }
}

interface CourseCourseNameRouteChildren {
  CourseCourseNameSettingsRoute: typeof CourseCourseNameSettingsRoute
  CourseCourseNameIndexRoute: typeof CourseCourseNameIndexRoute
  CourseCourseNameLectureLectureDayPreviewRoute: typeof CourseCourseNameLectureLectureDayPreviewRoute
  CourseCourseNameLectureLectureDayIndexRoute: typeof CourseCourseNameLectureLectureDayIndexRoute
  CourseCourseNameModulesModuleNameAssignmentAssignmentNameRoute: typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameRoute
  CourseCourseNameModulesModuleNamePagePageNameRoute: typeof CourseCourseNameModulesModuleNamePagePageNameRoute
  CourseCourseNameModulesModuleNameQuizQuizNameRoute: typeof CourseCourseNameModulesModuleNameQuizQuizNameRoute
  CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRoute: typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRoute
  CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRoute: typeof CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRoute
  CourseCourseNameModulesModuleNamePagePageNameHistoryRoute: typeof CourseCourseNameModulesModuleNamePagePageNameHistoryRoute
  CourseCourseNameModulesModuleNameQuizQuizNameCompareRoute: typeof CourseCourseNameModulesModuleNameQuizQuizNameCompareRoute
  CourseCourseNameModulesModuleNameQuizQuizNameHistoryRoute: typeof CourseCourseNameModulesModuleNameQuizQuizNameHistoryRoute
}

const CourseCourseNameRouteChildren: CourseCourseNameRouteChildren = {
  CourseCourseNameSettingsRoute: CourseCourseNameSettingsRoute,
  CourseCourseNameIndexRoute: CourseCourseNameIndexRoute,
  CourseCourseNameLectureLectureDayPreviewRoute:
    CourseCourseNameLectureLectureDayPreviewRoute,
  CourseCourseNameLectureLectureDayIndexRoute:
    CourseCourseNameLectureLectureDayIndexRoute,
  CourseCourseNameModulesModuleNameAssignmentAssignmentNameRoute:
    CourseCourseNameModulesModuleNameAssignmentAssignmentNameRoute,
  CourseCourseNameModulesModuleNamePagePageNameRoute:
    CourseCourseNameModulesModuleNamePagePageNameRoute,
  CourseCourseNameModulesModuleNameQuizQuizNameRoute:
    CourseCourseNameModulesModuleNameQuizQuizNameRoute,
  CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRoute:
    CourseCourseNameModulesModuleNameAssignmentAssignmentNameCompareRoute,
  CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRoute:
    CourseCourseNameModulesModuleNameAssignmentAssignmentNameHistoryRoute,
  CourseCourseNameModulesModuleNamePagePageNameHistoryRoute:
    CourseCourseNameModulesModuleNamePagePageNameHistoryRoute,
  CourseCourseNameModulesModuleNameQuizQuizNameCompareRoute:
    CourseCourseNameModulesModuleNameQuizQuizNameCompareRoute,
  CourseCourseNameModulesModuleNameQuizQuizNameHistoryRoute:
    CourseCourseNameModulesModuleNameQuizQuizNameHistoryRoute,
}

const CourseCourseNameRouteWithChildren =
  CourseCourseNameRoute._addFileChildren(CourseCourseNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorsRoute: ErrorsRoute,
  ApiCoursesRoute: ApiCoursesRoute,
  CourseCourseNameRoute: CourseCourseNameRouteWithChildren,
  ApiCanvasSplatRoute: ApiCanvasSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
